# Generated by Django 4.2.11 on 2024-03-20 09:09

from django.db import migrations, models
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_count_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(ultis.helper.custom_blog_image_path, *(), **{'path': 'image'})),
        ),
    ]
