# Generated by Django 4.2.11 on 2024-03-20 09:26

from django.db import migrations, models
import django.db.models.deletion
import functools
import ultis.helper
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=functools.partial(ultis.helper.custom_comment_image_path, *(), **{'path': 'image'}))),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
