# Generated by Django 4.2.11 on 2024-03-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file_url',
            new_name='file',
        ),
    ]
