# Generated by Django 4.2.11 on 2024-03-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_file_url_fileupload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file_type',
            new_name='file_content_type',
        ),
    ]
