# Generated by Django 4.2.11 on 2024-03-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_file_type_fileupload_file_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
