# Generated by Django 4.2.11 on 2024-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_fileupload_is_active_alter_fileupload_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test'),
        ),
    ]
