# Generated by Django 4.2.11 on 2024-03-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='upload_finished_at',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='video_duration',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='video_height',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='video_width',
        ),
    ]
