# Generated by Django 4.2.11 on 2024-03-25 07:40

from django.db import migrations, models
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(ultis.helper.custom_media_file_path, *(), **{'path': 'image'})),
        ),
    ]
