# Generated by Django 4.2.11 on 2024-03-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_fileupload_file_fileupload_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='avatar',
            new_name='file',
        ),
    ]
