# Generated by Django 4.2.11 on 2024-03-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_avatar_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
    ]
