# Generated by Django 4.2.11 on 2024-03-25 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_remove_fileupload_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(ultis.helper.custom_blog_image_path, *(), **{'path': 'image'})),
        ),
    ]
