# Generated by Django 4.2.11 on 2024-03-25 09:05

from django.db import migrations, models
import functools
import ultis.helper


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(ultis.helper.custom_media_img_path, *(), **{'path': 'image'})),
        ),
    ]
