# Generated by Django 4.2.11 on 2024-03-20 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_avatar_alter_customuser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterAvatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(upload_to='letter-avatar-images')),
            ],
        ),
    ]
