# Generated by Django 4.2.11 on 2024-03-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_letteravatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
