# Generated by Django 4.2.11 on 2024-03-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
